
server:
  port: 8081
spring:
  config:
    import: configserver:http://localhost:8085
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/cwdmicro
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-84565945.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oafezcjspoUxjW815d7
            client-secret: GSzAPK0yrzwKXnxZ677HYdbMxU1qzpCoSpCATVooskf_Lyk6zvKVaBnkx6dntSR_
okta:
  oauth2:
    issuer: https://dev-84565945.okta.com/oauth2/default
    audience: api://default

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0s





#  profiles:
#    active: prod

#eureka:
#  instance:
#    ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka



